######################## default configuration ####################
baseURL = "https://cacpucv-dev.github.io/beta/"
title = "Centro Acción Climática PUCV"
theme = "omega"
# google analytics
googleAnalytics = "" # example : UA-123-45
[markup.goldmark.renderer]
unsafe= true

######################### navigation ##############################

[[menu.main]]
name = "Nosotros"
pre = "#"
URL = "nosotros"
weight = 1

[[menu.main]]
name = "Investigación"
pre = "#"
URL = "#"
weight = 2

[[menu.main]]
name = "Proyectos"
pre = ""
URL = "#"
weight = 3

[[menu.main]]
name = "Publicaciones"
pre = ""
URL = "#"
weight = 4

[[menu.main]]
name = "Divulgación"
pre = ""
URL = "#"
weight = 5

[[menu.main]]
name = "Actividades"
pre = "#"
URL = "#"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo-cac-pucv.svg"
logo_width = "400px"
# Meta data
description = "Centro de Acción Climática PUCV - Centro de investigación orientado a impulsar acciones climáticas que contribuyan a la resiliencia climática a nivel, nacional regional y local."
author = "Centro de Acción Climática PUCV"
# contact info
contact_info = "Antonio Bellet 314<br>Providencia<br>Región Metropolitana"
# Preloader
preloader = true
# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDcYmkpfUJlz82RUknm_QR07ZBtmATaViE"
map_center_lat = "-33.424609014672505"
map_center_lng = "-70.62582726335388"
map_position_lat = "-33.4247638"
map_position_lng = "-70.6213848"
map_marker = "images/map-marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################

[[params.social]]
title = "twitter"
icon = "fa-twitter" # fontawesome icon pack v4.7 https://fontawesome.com/v4.7.0/icons/
link = "https://twitter.com/accionclimapucv"
